version: '3'

services:
  db:
    image: postgres:13
    container_name: docker-postgresql
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    ports:
      - 5430:5432
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

volumes:
  postgresql-volume: { }
